#!/bin/bash
# Backup files from local computer to network storage.

set -euo pipefail

# Magic variable for duration
SECONDS=0

share=/Volumes/Denis
dst=$share/backup/macos/$(date +%Y_%m_%d)

echo "Starting..."

echo -n "Create destination directory"
mkdir -p $dst
echo ": done"

echo -n "Archive configs and scripts"
tar -czf $dst/configs.tar.gz -C $HOME \
    .local/bin \
    .config/starship.toml \
    .kube \
    .notable \
    .ssh \
    Documents/*.kdbx \
    .zsh_aliases \
    .zshrc \
    .inputrc \
    .gitconfig \
    .gitignore
echo ": done"

dirs=( Dev Documents )
for dir in "${dirs[@]}"; do
    echo -n "Archive $dir"
    tar -czf $dst/$dir.tar.gz -C $HOME $dir
    echo ": done"
done

duration=$SECONDS
echo "Finished in $(($duration / 60))m $(($duration % 60))s"
