#!/bin/bash
# Backup files from local computer to network storage.

set -euo pipefail

echo -n "Set password for configs: "
read -s password

# Magic variable for duration
SECONDS=0

nfs=$HOME/mnt/denis
dst=$nfs/backup/linux/$(date +%Y_%m_%d)

echo "Starting..."

echo -n "Mount remote storage"
mount $nfs
echo ": done"

echo -n "Create destination directory"
mkdir -p $dst
echo ": done"

echo -n "Archive configs and scripts"
tar -c -C $HOME \
    .config/openvpn \
    .notable \
    .ssh | \
    openssl aes-256-cbc -md sha512 -iter 1000 -pbkdf2 -salt \
    -k "$password" \
    -out "$dst/configs.tar.enc"
echo ": done"

dirs=( dev etc )
for dir in "${dirs[@]}"; do
    echo -n "Ensure permissions $dir"
    sudo chown -R $USER:$USER $dir
    echo -n "Archive $dir"
    tar -cz -C $HOME $dir | \
    openssl aes-256-cbc -md sha512 -iter 1000 -pbkdf2 -salt \
    -k "$password" \
    -out "$dst/$dir.tar.gz.enc"
    echo ": done"
done

duration=$SECONDS
echo "Finished in $(($duration / 60))m $(($duration % 60))s"
