#!/bin/bash
# Backup files from local computer to network storage.

set -euo pipefail

echo -n "Set password for configs: "
read -s password

# Magic variable for duration
SECONDS=0

nfs=$HOME/mnt/denis
dst=$nfs/backup/linux/$(date +%Y_%m_%d)

echo "Starting..."

echo -n "Mount remote storage"
mount $nfs
echo ": done"

echo -n "Create destination directory"
mkdir -p $dst
echo ": done"

echo -n "Archive configs and scripts"
tar -cz -C $HOME \
    .config/openvpn \
    .config/starship.toml \
    .notable \
    .ssh \
    .bash_aliases \
    .bashrc \
    .inputrc \
    .profile \
    .gitconfig \
    .gitignore | \
    openssl aes-256-cbc -md sha512 -iter 1000 -pbkdf2 -salt \
    -k "$password" \
    -out "$dst/configs.tar.gz.enc"
echo ": done"

dirs=( dev )
for dir in "${dirs[@]}"; do
    echo -n "Archive $dir"
    tar -czf $dst/$dir.tar.gz -C $HOME $dir
    echo ": done"
done

duration=$SECONDS
echo "Finished in $(($duration / 60))m $(($duration % 60))s"
