#!/bin/bash
# Change default camera zoom.
#
# Install tools:
# sudo apt install v4l-utils
#
# Find the appropriate device:
# for dev in /dev/video*; do echo $dev; v4l2-ctl -d $dev --list-ctrls; done

zoom=${1:-130}
device=/dev/video4

echo "Setting zoom for $device to $zoom"
v4l2-ctl -d $device --set-ctrl zoom_absolute=${zoom}
