#!/usr/bin/env bash
# Run tmux with a few gping in separate panes. Ping each IP gateway from
# the routing table and 1.1.1.1 as an indicator for external Internet.
set -euo pipefail

if ! tmux has-session -t main 2>/dev/null; then
    tmux new-session -d -s main
fi

defaultgw=$(
    ip route show default | \
    grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'
)
vpn_on=$(host gitlab.booking.com &> /dev/null && echo true || echo false)

tmux send-keys -t "main:0.0" "gping --watch-interval 1 --buffer 300 $defaultgw"
tmux split-window -v -t main
if [[ $vpn_on == "true" ]]; then
    tmux send-keys -t "main:0.1" "gping --watch-interval 1 --buffer 300 gitlab.booking.com"
    tmux split-window -v -t main
fi
tmux send-keys -t "main:0.2" "gping --watch-interval 1 --buffer 300 1.1.1.1"

tmux set-window-option synchronize-panes
tmux select-layout -t main even-vertical
tmux attach-session -t main
