#!/bin/bash
# Backup files from local computer to network storage.

set -euo pipefail

# Magic variable for duration
SECONDS=0

nfs=$HOME/mnt/denis
dst=$nfs/backup/$(date +%Y_%m_%d)

echo "Starting..."

echo -n "Mount remote storage"
mount $nfs
echo ": done"

echo -n "Create destination directory"
mkdir -p $dst
echo ": done"

echo -n "Archive configs and scripts"
tar -czf $dst/configs.tar.gz -C /home/tetafro \
    .local/bin \
    .config/openvpn \
    .kube \
    .notable \
    .ssh \
    docs/passwd.kdbx \
    .bash_aliases \
    .bashrc \
    .inputrc \
    .profile \
    .gitconfig \
    .gitignore
echo ": done"

dirs=( dev docs etc )
for dir in "${dirs[@]}"; do
    echo -n "Archive $dir"
    tar -czf $dst/$dir.tar.gz -C /home/tetafro/ $dir
    echo ": done"
done

duration=$SECONDS
echo "Finished in $(($duration / 60))m $(($duration % 60))s"
