#!/bin/bash
# Update local golang installation to the latest version.

set -euo pipefail

echo -n 'Downloading... '
version=$(curl -s https://golang.org/VERSION?m=text)
curl -sL -o /tmp/go.tar.gz https://dl.google.com/go/${version}.linux-amd64.tar.gz
echo 'DONE'

echo -n 'Installing... '
sudo rm -rf /usr/local/go/
sudo tar -C /usr/local -xzf /tmp/go.tar.gz
rm -f /tmp/go.tar.gz
echo 'DONE'
