#!/bin/bash
# Update local golang installation to the latest version.

set -euo pipefail

if [[ $# -eq 1 ]]; then
    version=$1
else
    version=$(curl -s "https://go.dev/VERSION?m=text" | head -1)
fi
echo "Target version: $version"

echo -n "Downloading... "
curl -sL -o /tmp/go.tar.gz https://go.dev/dl/go${version}.linux-amd64.tar.gz
echo "Done"

echo -n "Installing... "
sudo rm -rf /usr/local/go/
sudo tar -C /usr/local -xzf /tmp/go.tar.gz
rm -f /tmp/go.tar.gz
echo "Done"
