#!/bin/bash
set -euo pipefail

cd $HOME/notes

if [ -z "$(git status --porcelain)" ]; then
    echo "No local changes, pull from remote"
    git pull
    exit 0
fi

echo "Pull from remote"
git pull

echo "Save current changes"
git add .
git commit -m "$(date +%H:%M\ %d-%m-%Y)"
git push
