#!/bin/bash
# Run which + cat for a file.

last_arg=${!#}
if [[ "$last_arg" == "-h" || $last_arg == "--help" ]]; then
    echo "USAGE:"
    echo "  wat [COMMAND]"
    exit 0
fi

cmd=$1

# Get alias - find the declaration and all following lines that
# start with a space
alias=$(awk -v cmd="$cmd" '
    $0 ~ "^alias " cmd "=" {
        print
        in_alias=1
        next
    }
    in_alias && /^ / {
        print
        next
    }
    in_alias { in_alias=0 }
' ~/.bash_aliases)
if [[ ! -z "$alias" ]]; then
    echo "$alias"
    exit 0
fi

file=$(which "$cmd")
if [[ -z "$file" ]]; then
    echo "Not found"
    exit 1
fi

mime=$(file --brief --dereference --mime-type "$file" | sed 's|/.*||')
if [[ "$mime" != "text" ]]; then
    echo "Binary file: $file"
    exit 0
fi

echo "File: $file"
show_cmd=cat
if [ "$(command -v bat)" ]; then
    show_cmd="bat --plain --paging=never"
fi
$show_cmd "$file"
